  swagger: '2.0'
  info:
    title: Cloud Endpoints + Cloud Run
    description: Sample API on Cloud Endpoints with a Cloud Run backend
    version: 1.0.0
  host: bmi-service-v1-u7naiutwtq-uc.a.run.app
  schemes:
    - https
  produces:
    - application/json
  x-google-backend:
    address: https://bmi-service-v1-u7naiutwtq-uc.a.run.app
    protocol: h2
  paths:
    /bmi:
      get:
        summary: Getting height and weight
        operationId: bmi
        x-google-backend:
          address: https://bmi-service-v1-u7naiutwtq-uc.a.run.app/bmi
          path_translation: APPEND_PATH_TO_ADDRESS  
        responses:
          '200':
            description: A successful response
            schema:
              type: string
      
